apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: model-prod
  namespace: argocd
spec:
  description: 'Project for the FastAPI development environment'
  sourceRepos:
    - '*'
  destinations:
    - namespace: argocd
      server: 'https://kubernetes.default.svc'
    - namespace: model-prod
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
